### ISSUE TITLE
Handling von Datenfehlern

### ISSUE THREAD

**Issue by Ubetterbisoft** [TGM-HIT/sew9-2425-worttrainer-nribinin#1]
Wenn das Laden der Datei fehlschlägt oder die Datei beschädigt ist, könnte dies besser behandelt werden, z. B. durch Überprüfung, ob die Datei existiert, und durch Validierung der JSON-Daten.

**Comment by nribinin** [comment]
Danke für dein Issue. Ich werde mich umgehend damit befassen!

**Comment by nribinin** [comment]
Dein Issue wurde gefixt. Danke nocheinmal!
